server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://161.132.47.74:5432/SISCOPE_DEMO
    username: siscope-main
    password: 515c0p3
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000 # 30 segundos en milisegundos
      connection-timeout: 5000 # 5 segundos en milisegundos
      max-lifetime: 1800000 # 30 minutos en milisegundos

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: 161.132.47.74
    username: 515c0p3
    password: Niwde123$

app:
  ws:
    version: 1

