server:
  port: 8080
spring:
  datasource:
    name: oracle-cloud-datasource
    url: jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.us-ashburn-1.oraclecloud.com))(connect_data=(service_name=g9c5be2749dd264_bdsiscope_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
    username: admin
    password: Angelus_ps4$
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
  app:
    ws:
      version: 1

