server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://69.164.197.95:5432/SISCOPE
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none

app:
  ws:
    version: 1

